name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install linters
        run: |
          npm ci
          npm install --save-dev stylelint stylelint-config-standard htmlhint

      - name: Create Stylelint config
        run: |
          cat <<EOF > .stylelintrc.json
          {
            "extends": "stylelint-config-standard"
          }
          EOF

      - name: Create HTMLHint config
        run: |
          cat <<EOF > .htmlhintrc
          {
            "tagname-lowercase": true,
            "attr-lowercase": true,
            "attr-value-double-quotes": true,
            "doctype-first": true,
            "tag-pair": true,
            "spec-char-escape": true,
            "id-unique": true,
            "src-not-empty": true
          }
          EOF

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html" || true

      - name: Run Stylelint
        run: npx stylelint "**/*.css" || true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t bulakh/lab1bulakh:latest .
          docker push bulakh/lab1bulakh:latest
