name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Запускати workflow при пуші в гілку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Завантаження коду репозиторію

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t bulakh/lab1bulakh:latest .
          docker push bulakh/lab1bulakh:latest
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.253.62"
            docker stop lab1bulakh || true &&
            docker rm lab1bulakh || true &&
            docker pull bulakh/lab1bulakh:latest &&
            docker run -d -p 80:80 --name lab1bulakh bulakh/lab1bulakh:latest
          "
